
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 65
#define YY_END_OF_BUFFER 66
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[364] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       66,   63,   64,   36,    8,   15,   15,   34,   63,   30,
       40,   22,   38,   23,   33,   15,   24,   18,   42,   32,
       21,   27,   62,   62,   62,   31,   41,   46,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   28,   63,   39,    7,    6,    6,
        7,    3,    2,    2,   12,   12,   13,   12,   12,   10,
       12,   12,   12,   65,   65,   14,   65,   65,   35,   62,
       62,   20,   16,   43,   17,    0,    0,    4,    1,   17,
       18,    0,    0,   44,   29,   25,   26,   45,   62,   62,

       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   16,   62,   62,   62,   62,   62,   62,   62,   62,
       52,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       37,    6,    5,    2,    9,    0,    0,   10,    0,    0,
        0,    9,   11,    9,    0,    0,    0,    0,    0,    0,
        0,    0,   14,    0,    0,   17,    0,   17,    0,    0,
       17,   18,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   16,   62,   62,   62,   53,   62,   62,

       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   17,
        0,    0,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   51,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   19,   60,
       62,   62,   17,    0,   17,   62,   62,   62,   62,   62,
       62,   48,   62,   62,   62,   62,   16,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   16,   62,   62,   61,    0,   62,   59,   16,   62,

       62,   62,   62,   50,   62,   62,   62,   62,   62,   62,
       62,   62,   56,   57,   58,   62,   62,   62,   62,   49,
       16,    0,   62,   47,   62,   62,   62,   62,   62,   62,
       62,   62,   62,    0,    0,   62,   62,   62,   62,   62,
       62,    0,    0,   62,   62,   62,    0,    0,   62,    0,
        0,   62,    0,    0,    0,    0,    0,    0,    0,    0,
       55,   54,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    7,    8,    9,   10,   11,    1,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,    1,   21,   22,
       23,   24,   25,    1,   26,   26,   26,   26,   27,   26,
       26,   26,   28,   26,   26,   26,   26,   26,   26,   26,
       26,   26,   29,   26,   26,   26,   26,   26,   26,   26,
       30,   31,   32,   33,   34,    1,   35,   36,   37,   38,

       39,   40,   41,   42,   43,   26,   44,   45,   46,   47,
       48,   49,   26,   50,   51,   52,   53,   54,   55,   56,
       57,   58,   59,   60,   61,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[62] =
    {   0,
        1,    2,    2,    1,    3,    1,    3,    1,    4,    1,
        1,    5,    5,    1,    1,    1,    1,    1,    1,    6,
        1,    1,    1,    1,    1,    6,    6,    6,    6,    1,
        2,    1,    1,    4,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    1,    5,
        1
    } ;

static yyconst flex_int16_t yy_base[371] =
    {   0,
        0,    0,   59,   61,   63,   65,   75,    0,  136,    0,
      904,  905,  905,  880,  905,  905,  882,  905,  890,  905,
      905,  905,  885,  905,  181,  179,  188,  183,  905,   48,
      876,  185,  878,  180,  184,  905,  905,  905,  192,  194,
      205,  191,  201,  217,  206,  209,  211,  238,  243,  193,
      246,  225,  213,  196,  905,  837,  905,  905,  905,  893,
      876,  905,  905,  891,  890,  269,  889,  888,  277,  905,
      302,  308,  309,  905,  263,  905,  312,  322,  905,  870,
        0,  905,  905,  905,  267,  275,  850,  905,  905,  298,
      316,  331,  200,  905,  905,  905,  905,  905,  300,  294,

      306,  311,  315,  282,  321,  301,  318,  338,  343,  325,
      195,  327,  334,  344,  347,  345,  348,  354,  351,  355,
      868,  356,  357,  359,  361,  362,  366,  244,  367,  249,
      364,  371,  368,  363,  378,  373,  380,  369,  394,  404,
      905,  905,  905,  905,  905,  426,  433,  905,  447,  453,
      452,  905,  905,  905,  467,  474,  483,  504,  510,  516,
      524,  475,  905,  532,  533,  405,  867,  469,  839,  865,
      407,  414,  422,  425,  423,  445,  471,  480,  481,  512,
      522,  508,  443,  513,  514,  523,  526,  528,  529,  530,
      534,  536,  537,  864,  539,  543,  540,  550,  553,  554,

      548,  556,  557,  558,  559,  560,  562,  563,  564,  566,
      570,  561,  575,  576,  581,  579,  582,  586,  588,  596,
      842,  583,  589,  594,  599,  605,  607,  609,  612,  611,
      614,  616,  617,  619,  622,  862,  623,  620,  624,  625,
      627,  626,  629,  630,  631,  638,  643,  632,  641,  642,
      634,  654,  659,  655,  661,  662,  663,  668,  861,  860,
      669,  667,  673,  827,  674,  670,  675,  671,  679,  681,
      687,  857,  682,  683,  691,  693,  690,  695,  700,  703,
      431,  704,  705,  706,  707,  712,  714,  716,  717,  718,
      720,  722,  719,  725,  854,  831,  727,  850,   54,  728,

      731,  734,  736,  844,  735,  737,  743,  739,  744,  746,
      751,  747,  843,  839,  824,  752,  754,  761,  760,  905,
      374,  795,  755,  822,  764,  763,  769,  775,  776,  771,
      777,  778,  784,  792,  786,  781,  773,  789,  791,  793,
      786,  799,  780,  794,  797,  266,  781,  812,  796,  776,
      777,  802,  780,  768,  494,  477,  415,  349,  171,  167,
      905,  905,  905,  845,  851,  854,  859,  865,  869,  872
    } ;

static yyconst flex_int16_t yy_def[371] =
    {   0,
      363,    1,  364,  364,  365,  365,  363,    7,  363,    9,
      363,  363,  363,  363,  363,  363,  366,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  366,  366,  366,  363,  363,  363,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  367,  363,  363,  367,  363,
      367,  367,  368,  363,  369,  363,  369,  369,  363,  366,
      370,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  363,  363,  366,  366,

      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      363,  363,  363,  363,  363,  367,  367,  363,  367,  367,
      363,  363,  363,  363,  367,  367,  367,  367,  367,  367,
      367,  369,  363,  369,  369,  363,  363,  363,  363,  363,
      363,  363,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,

      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  363,
      363,  363,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  363,  363,  363,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  363,  366,  366,  366,  366,

      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  363,
      366,  363,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  363,  363,  366,  366,  366,  366,  366,
      366,  363,  363,  366,  366,  366,  363,  363,  366,  363,
      363,  366,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  363,    0,  363,  363,  363,  363,  363,  363,  363
    } ;

static yyconst flex_int16_t yy_nxt[967] =
    {   0,
       12,   12,   13,   12,   12,   14,   15,   16,   17,   18,
       19,   20,   21,   22,   23,   24,   25,   26,   27,   28,
       29,   30,   31,   32,   16,   33,   33,   34,   35,   36,
       12,   37,   38,   33,   39,   40,   41,   42,   43,   44,
       45,   33,   46,   33,   47,   33,   48,   33,   49,   50,
       51,   52,   33,   53,   54,   33,   33,   33,   55,   56,
       57,   59,   60,   59,   60,   63,   64,   63,   64,   94,
       95,  322,   61,   81,   61,   65,   66,   67,   68,   69,
       65,   70,   65,   65,   65,   65,   65,   65,   65,   65,
       65,   65,   65,   65,   71,   65,   65,   65,   65,   65,

       72,   72,   72,   72,   65,   73,   65,   65,   65,   72,
       72,   72,   72,   72,   72,   72,   72,   72,   72,   72,
       72,   72,   72,   72,   72,   72,   72,   72,   72,   72,
       72,   72,   72,   65,   65,   65,   74,   74,   74,   74,
       75,   74,   76,   74,   74,   74,   74,   74,   74,   74,
       74,   74,   74,   74,   74,   77,   74,   74,   74,   74,
       74,   78,   78,   78,   78,   74,   74,   74,   74,   74,
       78,   78,   78,   78,   78,   78,   78,   78,   78,   78,
       78,   78,   78,   78,   78,   78,   78,   78,   78,   78,
       78,   78,   78,   78,   74,   74,   74,   83,   85,   81,

       90,   88,   91,   81,   84,   86,   89,   97,   98,   92,
       81,   81,   81,   81,   81,   81,   93,   86,  362,  172,
       81,   92,  361,   87,   81,   81,   99,  102,   81,  111,
       81,  131,   81,   93,  186,  100,   81,  140,  112,  107,
      101,  104,  103,  105,   81,  113,  108,  114,  121,  109,
      106,  116,  110,  120,  122,  123,  115,   81,  124,  117,
      139,  118,   81,   81,  119,   81,  137,  162,   81,  163,
      146,  145,  125,  147,  138,  148,  126,  128,  146,  145,
      202,  147,  164,  148,  205,   81,  166,  132,  149,  167,
      127,  167,  129,   86,  168,  130,  149,  133,  134,  151,

      135,   81,  136,  146,  145,   86,  147,  151,  148,  146,
      145,  154,  147,   81,  148,  155,  162,   85,  163,   81,
       81,  149,  156,  349,   86,   81,  162,  149,  163,  178,
       81,  164,  151,   90,   81,   91,   86,   81,  151,  157,
       81,  164,   92,  174,   81,  170,   81,  170,  158,   93,
      171,  173,  180,   81,   92,  159,  175,   81,  160,  179,
      161,  176,   81,   81,   81,  177,   81,   81,  181,  182,
       81,  185,  183,   81,   81,   81,   81,  184,   81,  187,
       81,   81,   81,   81,  188,   81,   81,   81,   81,  191,
       81,  334,   81,   81,  192,  360,  189,   81,  190,   81,

      194,  193,  208,  215,  196,  199,  195,  197,  198,  203,
      201,  210,  200,   81,  204,  206,  194,  209,  207,  212,
      211,  216,  213,   81,  166,  194,  171,  146,  363,  214,
      147,   86,  148,  172,  146,  363,  217,  147,  218,  148,
      222,   81,   81,   86,   81,  149,  219,   93,  146,  363,
       81,  147,  149,  148,  146,  363,  151,  147,  155,  148,
      223,  359,   81,  151,   81,  156,  149,  224,  146,  363,
      309,  147,  149,  148,  225,  146,  363,  151,  147,  162,
      148,  163,  157,  151,  146,  363,  149,  147,  220,  148,
       81,  158,  194,  149,  164,   86,  226,  151,  159,   81,

       81,  160,  149,  161,  151,  146,  363,   86,  147,  227,
      148,  146,  363,  151,  147,  229,  148,  146,  363,  358,
      147,  357,  148,  149,  228,  146,  363,   81,  147,  149,
      148,   81,   81,   81,  151,  149,  162,  162,  163,  163,
      151,   81,   81,  149,  230,   81,  151,   81,   81,   81,
      194,  164,  164,   81,  151,   81,   81,  234,   81,   81,
      194,  235,   81,  231,  232,  233,  236,   81,  237,   81,
      239,  240,   81,   81,  194,   81,   81,   81,   81,   81,
       81,   81,   81,   81,  238,   81,  194,  241,  244,   81,
      242,  243,  194,  194,   81,   81,  245,  256,   81,  246,

       81,   81,  265,  249,  254,   81,  253,   81,   81,  248,
      247,  251,  250,   81,  252,  263,  222,  259,   81,  260,
      261,  255,   86,  257,   81,  194,   81,  258,   81,  266,
       81,   81,  262,   81,   86,   81,   81,  268,   81,   81,
      267,   81,   81,   81,   81,   81,   81,  271,   81,   81,
       81,   81,  194,   81,  269,  194,  270,   81,  259,  273,
       81,   81,   81,  280,  272,  278,  275,  194,  277,  276,
      285,  274,  283,   81,   81,  279,  194,  284,   81,  281,
       81,   81,   81,  286,  282,  194,   81,   81,   81,   81,
       81,  287,  263,  265,   81,  289,  288,  290,   81,   86,

       81,   81,   81,  291,  194,  295,   81,  222,  297,   81,
       81,   86,   81,  300,   81,  298,  299,  292,  293,   81,
      294,  301,   81,   81,   81,   81,   81,  303,  302,  304,
      305,   81,  194,   81,  306,   81,   81,   81,   81,   81,
      307,   81,  194,  312,   81,  310,   81,   81,  313,  308,
       81,  194,  315,   81,   81,   81,   81,  311,   81,  194,
      314,  318,   81,   81,  323,   81,   81,  319,  316,  317,
       81,   81,  194,   81,   81,  327,  321,  324,  328,   81,
       81,  326,   81,   81,  194,  194,  325,  194,   81,  194,
       81,  330,   81,  194,   81,   81,   81,   81,  329,  332,

       81,  331,  194,   81,  333,   81,  194,  337,   81,  336,
       81,  338,   81,   81,  339,   81,   81,  356,  355,  194,
      345,   81,  194,  340,  341,  354,  353,  194,  194,  351,
      350,  348,  344,  347,  352,  346,  194,  194,  343,  194,
      342,   81,  335,   81,  194,   58,   58,   58,   58,   58,
       58,   62,   62,   62,   62,   62,   62,   80,   81,   80,
      150,  150,   81,   81,  150,  153,  153,  153,  153,   81,
      153,  165,  320,   81,  165,   81,   81,   81,  296,   81,
       81,   81,  264,   81,  171,  221,  168,   81,  169,   81,
      152,  145,  145,  144,  143,  142,  141,   81,   96,   83,

       82,   81,   79,  363,   11,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363
    } ;

static yyconst flex_int16_t yy_chk[967] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    3,    4,    4,    5,    5,    6,    6,   30,
       30,  299,    3,  299,    4,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,

        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,   25,   26,   34,

       28,   27,   28,   35,   25,   26,   27,   32,   32,   28,
       42,   39,   50,   40,  111,   54,   28,   26,  360,   93,
       43,   28,  359,   26,   41,   45,   34,   39,   46,   42,
       47,   50,   53,   93,  111,   35,   44,   54,   42,   41,
       35,   40,   39,   40,   52,   43,   41,   43,   46,   41,
       40,   44,   41,   45,   46,   46,   43,   48,   47,   44,
       53,   44,   49,  128,   44,   51,   52,   75,  130,   75,
       66,   66,   48,   66,   52,   66,   48,   49,   69,   69,
      128,   69,   75,   69,  130,  346,   85,   51,   66,   86,
       48,   86,   49,   85,   86,   49,   69,   51,   51,   66,

       51,  104,   51,   71,   71,   85,   71,   69,   71,   72,
       72,   73,   72,  100,   72,   73,   77,   90,   77,   99,
      106,   71,   73,  346,   90,  101,   78,   72,   78,  104,
      102,   77,   71,   91,  103,   91,   90,  107,   72,   73,
      105,   78,   91,  100,  110,   92,  112,   92,   73,   91,
       92,   99,  106,  113,   91,   73,  101,  108,   73,  105,
       73,  102,  109,  114,  116,  103,  115,  117,  107,  107,
      119,  110,  108,  118,  120,  122,  123,  109,  124,  112,
      125,  126,  134,  131,  113,  127,  129,  133,  138,  116,
      132,  321,  136,  321,  117,  358,  114,  135,  115,  137,

      119,  118,  133,  138,  122,  124,  120,  123,  123,  129,
      127,  134,  125,  139,  129,  131,  126,  133,  132,  136,
      135,  138,  137,  140,  166,  138,  171,  146,  146,  137,
      146,  166,  146,  172,  147,  147,  139,  147,  139,  147,
      171,  173,  175,  166,  174,  146,  140,  172,  149,  149,
      281,  149,  147,  149,  150,  150,  146,  150,  151,  150,
      173,  357,  183,  147,  176,  151,  149,  174,  155,  155,
      281,  155,  150,  155,  175,  156,  156,  149,  156,  162,
      156,  162,  151,  150,  157,  157,  155,  157,  168,  157,
      177,  151,  183,  156,  162,  168,  176,  155,  151,  178,

      179,  151,  157,  151,  156,  158,  158,  168,  158,  177,
      158,  159,  159,  157,  159,  179,  159,  160,  160,  356,
      160,  355,  160,  158,  178,  161,  161,  182,  161,  159,
      161,  180,  184,  185,  158,  160,  164,  165,  164,  165,
      159,  181,  186,  161,  182,  187,  160,  188,  189,  190,
      180,  164,  165,  191,  161,  192,  193,  186,  195,  197,
      181,  187,  196,  184,  185,  185,  188,  201,  190,  198,
      192,  193,  199,  200,  189,  202,  203,  204,  205,  206,
      212,  207,  208,  209,  191,  210,  195,  196,  198,  211,
      196,  197,  201,  199,  213,  214,  200,  212,  216,  202,

      215,  217,  222,  205,  210,  218,  209,  219,  223,  204,
      203,  207,  206,  224,  208,  220,  222,  216,  225,  217,
      218,  211,  220,  214,  226,  213,  227,  215,  228,  223,
      230,  229,  219,  231,  220,  232,  233,  225,  234,  238,
      224,  235,  237,  239,  240,  242,  241,  228,  243,  244,
      245,  248,  230,  251,  226,  229,  227,  246,  238,  233,
      249,  250,  247,  243,  231,  241,  235,  232,  239,  237,
      248,  234,  246,  252,  254,  242,  240,  247,  253,  244,
      255,  256,  257,  249,  245,  251,  262,  258,  261,  266,
      268,  250,  263,  265,  267,  253,  252,  255,  269,  263,

      270,  273,  274,  256,  254,  262,  271,  265,  266,  277,
      275,  263,  276,  269,  278,  267,  268,  257,  258,  279,
      261,  271,  280,  282,  283,  284,  285,  274,  273,  275,
      276,  286,  270,  287,  277,  288,  289,  290,  293,  291,
      278,  292,  282,  285,  294,  283,  297,  300,  286,  280,
      301,  279,  288,  302,  305,  303,  306,  284,  308,  290,
      287,  293,  307,  309,  300,  310,  312,  294,  289,  291,
      311,  316,  292,  317,  323,  308,  297,  301,  309,  319,
      318,  307,  326,  325,  310,  305,  302,  303,  327,  311,
      330,  316,  337,  306,  328,  329,  331,  332,  312,  318,

      336,  317,  325,  333,  319,  341,  323,  327,  338,  326,
      339,  328,  340,  344,  329,  349,  345,  354,  353,  330,
      337,  352,  333,  331,  332,  351,  350,  338,  339,  348,
      347,  343,  336,  342,  349,  340,  345,  341,  335,  352,
      334,  324,  322,  315,  344,  364,  364,  364,  364,  364,
      364,  365,  365,  365,  365,  365,  365,  366,  314,  366,
      367,  367,  313,  304,  367,  368,  368,  368,  368,  298,
      368,  369,  296,  295,  369,  370,  272,  370,  264,  260,
      259,  236,  221,  194,  170,  169,  167,  121,   87,   80,
       68,   67,   65,   64,   61,   60,   56,   33,   31,   23,

       19,   17,   14,   11,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "jucompiler.l"




#line 12 "jucompiler.l"
#include<stdio.h>
int line_count=1;
int col_count=0;
int ini_line=1; //guarda linha em que começa comentario ou string
int ini_col=1; //guarda coluna em que começa comentario ou string
#line 793 "lex.yy.c"

#define INITIAL 0
#define COMMENT 1
#define COMMENT2 2
#define STR 3
#define ERRO 4

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 19 "jucompiler.l"


#line 982 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 364 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 905 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 21 "jucompiler.l"
{BEGIN COMMENT2;col_count=col_count+yyleng;}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 22 "jucompiler.l"
{BEGIN 0;line_count++;} //regressar ao normal
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 23 "jucompiler.l"
{col_count=col_count+yyleng;} //ignorar
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 25 "jucompiler.l"
{BEGIN COMMENT;ini_line=line_count;ini_col = col_count+1;col_count=col_count+yyleng;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 26 "jucompiler.l"
{BEGIN 0;col_count=col_count+yyleng;} //regressar ao normal
	YY_BREAK
case YY_STATE_EOF(COMMENT):
#line 27 "jucompiler.l"
{printf("Line %d, col %d: unterminated comment\n",ini_line,ini_col);BEGIN 0;} //regressar ao normal
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 28 "jucompiler.l"
{line_count++;} //ignorar
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 29 "jucompiler.l"
{col_count=col_count+yyleng;} //ignorar
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 31 "jucompiler.l"
{BEGIN STR;ini_line=line_count;ini_col = col_count+1;col_count=col_count+yyleng;}
	YY_BREAK
case YY_STATE_EOF(STR):
#line 32 "jucompiler.l"
{printf("Line %d, col %d: unterminated string literal\n",ini_line,ini_col);BEGIN 0;}
	YY_BREAK
case 9:
/* rule 9 can match eol */
YY_RULE_SETUP
#line 33 "jucompiler.l"
{printf("Line %d, col %d: unterminated string literal\n",ini_line,ini_col);BEGIN 0;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 34 "jucompiler.l"
{printf("STRLIT(\"%s)\n",yytext);col_count=col_count+yyleng;BEGIN 0;}
	YY_BREAK
case 11:
/* rule 11 can match eol */
YY_RULE_SETUP
#line 35 "jucompiler.l"
{col_count++;printf("Line %d, col %d: invalid escape sequence (%s)\n",line_count,col_count,yytext);BEGIN ERRO;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 36 "jucompiler.l"
{col_count=col_count+yyleng;}
	YY_BREAK
case 13:
/* rule 13 can match eol */
YY_RULE_SETUP
#line 37 "jucompiler.l"
{line_count++;col_count=0;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 39 "jucompiler.l"
{printf("Line %d, col %d: unterminated string literal\n",ini_line,ini_col);BEGIN 0;}					
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 42 "jucompiler.l"
{col_count++;printf("Line %d, col %d: illegal character (%s)\n",line_count,col_count,yytext);}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 43 "jucompiler.l"
{printf("RESERVED(%s)\n",yytext);col_count=col_count+yyleng;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 44 "jucompiler.l"
{printf("REALLIT(%s)\n",yytext);}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 45 "jucompiler.l"
{printf("INTLIT(%s)\n",yytext);col_count=col_count+yyleng;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 46 "jucompiler.l"
{printf("BOOLLIT(%s)\n",yytext);col_count=col_count+yyleng;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 47 "jucompiler.l"
{printf("AND\n");col_count=col_count+yyleng;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 48 "jucompiler.l"
{printf("ASSIGN\n");col_count=col_count+yyleng;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 49 "jucompiler.l"
{printf("STAR\n");col_count=col_count+yyleng;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 50 "jucompiler.l"
{printf("COMMA\n");col_count=col_count+yyleng;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 51 "jucompiler.l"
{printf("DIV\n");col_count=col_count+yyleng;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 52 "jucompiler.l"
{printf("EQ\n");col_count=col_count+yyleng;}	
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 53 "jucompiler.l"
{printf("GE\n");col_count=col_count+yyleng;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 54 "jucompiler.l"
{printf("GT\n");col_count=col_count+yyleng;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 55 "jucompiler.l"
{printf("LBRACE\n");col_count=col_count+yyleng;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 56 "jucompiler.l"
{printf("LE\n");col_count=col_count+yyleng;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 57 "jucompiler.l"
{printf("LPAR\n");col_count=col_count+yyleng;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 58 "jucompiler.l"
{printf("LSQ\n");col_count=col_count+yyleng;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 59 "jucompiler.l"
{printf("LT\n");col_count=col_count+yyleng;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 60 "jucompiler.l"
{printf("MINUS\n");col_count=col_count+yyleng;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 61 "jucompiler.l"
{printf("MOD\n");col_count=col_count+yyleng;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 62 "jucompiler.l"
{printf("NE\n");col_count=col_count+yyleng;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 63 "jucompiler.l"
{printf("NOT\n");col_count=col_count+yyleng;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 64 "jucompiler.l"
{printf("OR\n");col_count=col_count+yyleng;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 65 "jucompiler.l"
{printf("PLUS\n");col_count=col_count+yyleng;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 66 "jucompiler.l"
{printf("RBRACE\n");col_count=col_count+yyleng;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 67 "jucompiler.l"
{printf("RPAR\n");col_count=col_count+yyleng;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 68 "jucompiler.l"
{printf("RSQ\n");col_count=col_count+yyleng;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 69 "jucompiler.l"
{printf("SEMICOLON\n");col_count=col_count+yyleng;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 70 "jucompiler.l"
{printf("ARROW\n");col_count=col_count+yyleng;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 71 "jucompiler.l"
{printf("LSHIFT\n");col_count=col_count+yyleng;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 72 "jucompiler.l"
{printf("RSHIFT\n");col_count=col_count+yyleng;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 73 "jucompiler.l"
{printf("XOR\n");col_count=col_count+yyleng;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 74 "jucompiler.l"
{printf("BOOL\n");col_count=col_count+yyleng;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 75 "jucompiler.l"
{printf("CLASS\n");col_count=col_count+yyleng;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 76 "jucompiler.l"
{printf("DOTLENGTH\n");col_count=col_count+yyleng;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 77 "jucompiler.l"
{printf("DOUBLE\n");col_count=col_count+yyleng;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 78 "jucompiler.l"
{printf("ELSE\n");col_count=col_count+yyleng;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 79 "jucompiler.l"
{printf("IF\n");col_count=col_count+yyleng;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 80 "jucompiler.l"
{printf("INT\n");col_count=col_count+yyleng;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 81 "jucompiler.l"
{printf("PRINT\n");col_count=col_count+yyleng;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 82 "jucompiler.l"
{printf("PARSEINT\n");col_count=col_count+yyleng;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 83 "jucompiler.l"
{printf("PUBLIC\n");col_count=col_count+yyleng;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 84 "jucompiler.l"
{printf("RETURN\n");col_count=col_count+yyleng;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 85 "jucompiler.l"
{printf("STATIC\n");col_count=col_count+yyleng;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 86 "jucompiler.l"
{printf("STRING\n");col_count=col_count+yyleng;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 87 "jucompiler.l"
{printf("VOID\n");col_count=col_count+yyleng;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 88 "jucompiler.l"
{printf("WHILE\n");col_count=col_count+yyleng;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 89 "jucompiler.l"
{printf("ID(%s)\n",yytext);col_count=col_count+yyleng;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 90 "jucompiler.l"
{col_count=col_count+yyleng;}
	YY_BREAK
case 64:
/* rule 64 can match eol */
YY_RULE_SETUP
#line 91 "jucompiler.l"
{line_count++;col_count=0;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 94 "jucompiler.l"
ECHO;
	YY_BREAK
#line 1404 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMMENT2):
case YY_STATE_EOF(ERRO):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 364 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 364 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 363);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n, i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 94 "jucompiler.l"



int main()
{
	yylex();
	return 0;
}

int yywrap()
{
	return 1;
}
