
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 65
#define YY_END_OF_BUFFER 66
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[367] =
    {   0,
        0,    0,    0,    0,    0,    0,   14,   14,    0,    0,
       66,   64,   62,   63,   63,   35,    8,   61,   33,   64,
       29,   39,   21,   37,   22,   32,   64,   23,   17,   17,
       41,   31,   20,   26,   61,   61,   30,   40,   45,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   27,   64,   38,    7,    6,
        6,    7,    3,    2,    2,   14,   14,   13,   13,   12,
        9,   11,   10,   10,   65,   63,   34,   61,   61,   61,
       19,   15,   42,   16,    0,    4,    1,   16,    0,    0,
        0,   17,   17,    0,   43,   28,   24,   25,   44,   61,

       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   15,   61,   61,   61,   61,   61,   61,   61,
       61,   51,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   36,    6,    5,    2,   14,   14,   12,    9,   13,
       10,   61,   16,    0,    0,    0,   16,    0,    0,   16,
        0,   17,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   15,   61,   61,   61,   52,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,

       61,   61,   61,   61,   61,   61,   61,   61,   61,    0,
       16,   16,    0,   16,    0,    0,   16,   16,    0,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   50,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   18,   59,   61,   61,   16,
        0,    0,   16,   16,    0,   16,   61,   61,   61,   61,
       61,   61,   47,   61,   61,   61,   61,   15,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   15,   61,   61,   60,   16,    0,   16,   61,

       58,   15,   61,   61,   61,   61,   49,   61,   61,   61,
       61,   61,   61,   61,   61,   55,   56,   57,   61,   61,
       61,   61,   48,   15,    0,   61,   46,   61,   61,   61,
       61,   61,   61,   61,   61,   61,    0,    0,   61,   61,
       61,   61,   61,   61,    0,    0,   61,   61,   61,    0,
        0,   61,    0,    0,   61,    0,    0,    0,    0,    0,
        0,    0,    0,   54,   53,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    4,    5,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    6,    7,    8,    1,    9,   10,   11,    1,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   21,
       21,   21,   21,   21,   21,   21,   21,    1,   22,   23,
       24,   25,    1,    1,   26,   26,   26,   26,   27,   26,
       26,   26,   28,   26,   26,   26,   26,   26,   26,   26,
       26,   26,   29,   26,   26,   26,   26,   26,   26,   26,
       30,   31,   32,   33,   34,    1,   35,   36,   37,   38,

       39,   40,   41,   42,   43,   26,   44,   45,   46,   47,
       48,   49,   26,   50,   51,   52,   53,   54,   55,   56,
       57,   58,   59,   60,   61,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[62] =
    {   0,
        1,    1,    2,    1,    2,    1,    1,    1,    3,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    3,
        3,    1,    1,    1,    1,    3,    3,    3,    3,    1,
        1,    1,    1,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    1,    1,
        1
    } ;

static yyconst flex_int16_t yy_base[374] =
    {   0,
        0,    0,   59,   60,   63,   64,   73,   80,   84,   88,
      295, 1425, 1425, 1425,  289,  259, 1425,   86, 1425,  260,
     1425, 1425, 1425,  248, 1425,   55,   77,   80,   82,  105,
     1425,   47,  233,   88,  109,  128, 1425, 1425, 1425,  132,
      138,  119,  134,  142,  158,   60,  164,  152,  178,  170,
      186,  196,  182,  197,  208, 1425,  192, 1425, 1425, 1425,
      239,  222, 1425, 1425,  237,  253,  258, 1425,  234, 1425,
      254, 1425, 1425,  230, 1425, 1425, 1425,  219,  136,  220,
     1425, 1425, 1425,  252,  190, 1425, 1425,  254,  278,  293,
      282,  300,  304,  308, 1425, 1425, 1425, 1425, 1425,  230,

      240,  296,  300,  304,  308,  320,  312,  323,  328,  331,
      336,  342,  341,  352,  357,  356,  367,  371,  372,  375,
      383,  386,  389,  397,  394,  405,  408,  416,  422,  426,
      432,  436,  437,  442,  447,  455,  459,  465,  475,  476,
      486, 1425, 1425, 1425, 1425,  529,  536, 1425,  509, 1425,
     1425,  137,  530,  315,  480,  175,  545,  553,  130,  542,
      560,  568,  491,  548,  556,  562,  561,  572,  580,  577,
      585,  595,  470,  590,  598,  609,  535,  612,  608,  622,
      623,  628,  633,  497,  627,  641,  644,  649,  652,  660,
      666,  671,  670,  681,  687,  686,  692,  698,  704,  712,

      715,  716,  720,  726,  731,  736,  742,  747,  746,  154,
      692,  780,  178,  788,  790,  157,  792,  796,  800,  787,
      791,  792,  775,  795,  807,  803,  808,  811,  819,  827,
      830,  840,  824,  844,  850,  854,  858,  864,  868,  874,
      869,  879,  893,  897,  896,  908,  892,  907,  918,  923,
      919,  933,  936,  937,  947,  951,  952,  955,  967,  918,
      993,  164,  998, 1000, 1002, 1008,  991,  990, 1003, 1008,
     1002, 1020, 1014, 1019, 1030, 1024, 1035, 1034, 1040, 1046,
     1052, 1064, 1067, 1070, 1078, 1086, 1092, 1091, 1096, 1102,
     1113, 1108, 1116, 1126, 1129, 1130, 1111,  165, 1161, 1140,

     1141, 1144, 1156, 1152, 1155, 1166, 1167, 1171, 1177, 1181,
     1189, 1195, 1194, 1208, 1205, 1211, 1216, 1219, 1230, 1224,
     1236, 1240, 1425, 1253,  149, 1248, 1254, 1267, 1266, 1270,
     1271, 1283, 1286, 1282, 1294, 1298,  147,  141, 1297, 1302,
     1314, 1318, 1315, 1326,  146,  127, 1329, 1341, 1337,  115,
      145, 1349,  109,  108, 1352,  116,   92,  105,   84,   67,
       58,   49,   38, 1425, 1425, 1425, 1409, 1412, 1415, 1418,
       81, 1421,   74
    } ;

static yyconst flex_int16_t yy_def[374] =
    {   0,
      366,    1,  367,  367,  368,  368,  369,  369,  370,  370,
      366,  366,  366,  366,  366,  366,  366,  371,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  371,  371,  366,  366,  366,  371,
      371,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  372,  372,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,   41,  373,   41,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,   41,

       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,  366,  366,  366,  366,  372,  372,  366,  366,  366,
      366,  373,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,

       41,   41,   41,   41,   41,   41,   41,   41,   41,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,  366,
      366,  366,  366,  366,  366,  366,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,  366,  366,  366,   41,

       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,  366,   41,  366,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,  366,  366,   41,   41,
       41,   41,   41,   41,  366,  366,   41,   41,   41,  366,
      366,   41,  366,  366,   41,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,    0,  366,  366,  366,  366,
      366,  366,  366
    } ;

static yyconst flex_int16_t yy_nxt[1487] =
    {   0,
       12,   13,   14,   13,   15,   13,   16,   17,   18,   19,
       20,   21,   22,   23,   24,   25,   26,   27,   28,   29,
       30,   31,   32,   33,   34,   18,   18,   35,   36,   37,
       12,   38,   39,   18,   40,   41,   42,   43,   44,   45,
       46,   18,   47,   18,   48,   18,   49,   18,   50,   51,
       52,   53,   18,   54,   55,   18,   18,   18,   56,   57,
       58,   60,   60,   61,   61,   64,   64,   65,   65,   95,
       96,   82,   62,   62,   67,   68,   79,   69,   67,   83,
       70,   67,   68,   80,   69,   67,   73,   70,   74,  365,
       73,   75,   74,   86,   78,   75,   84,   84,   87,   88,

      364,   89,   89,   71,  363,   79,   79,  121,   90,   80,
       71,   98,   99,  362,   75,   91,   80,   78,   75,   78,
       90,   85,   88,   75,   92,   93,  361,   75,   79,   79,
       75,   90,  360,   75,   75,   75,   78,   75,   94,   75,
       78,  359,   78,   90,  152,  152,   78,   79,   79,  160,
      160,   79,   79,  108,  358,  100,  357,   79,   79,  356,
      109,   78,  354,  110,  353,   78,  111,  103,   80,  152,
      152,   78,  112,  211,  211,   80,  217,  217,  351,  101,
      350,  113,  104,   80,  102,  105,  114,  106,  115,   80,
       80,   80,  117,  346,  107,  345,  338,  116,   80,  125,

      118,   80,  119,  122,  129,  120,  323,   80,   80,  123,
      124,   80,  126,   80,   80,  298,  127,   80,  262,  130,
       80,  213,  131,  138,  132,   80,   80,   80,  156,   80,
      128,  139,  151,   80,   80,   80,  150,  133,   80,  145,
      144,  143,   80,   80,  140,   80,   80,  134,  135,  141,
      136,  142,  137,   80,  147,   80,   97,   80,  147,  147,
      148,  146,   82,  147,   80,  148,   80,   80,   80,   80,
       81,  153,  153,  157,  157,   80,   80,   80,  154,   80,
      158,  163,   77,  149,  146,  155,   80,   80,  149,  164,
      154,   76,  158,  146,  366,   88,   80,   89,   89,  366,

      146,  161,  161,  146,   90,  146,  366,  159,  366,  159,
      366,   91,  160,  160,  366,   91,   90,   88,  366,   92,
       92,   88,  366,   92,   93,  366,   90,  162,  162,  210,
       90,  210,  366,   94,  211,  211,  366,   94,   90,  366,
      366,   94,   90,   80,  366,   80,  165,   80,  366,   80,
      166,   80,   80,   80,  167,  168,   80,   80,  169,   80,
       80,   80,  173,  170,   80,  174,  366,   80,   80,   80,
       80,  366,   80,  171,  172,   80,   80,   80,   80,   80,
       80,  176,  175,   80,   80,   80,  366,   80,   80,   80,
       80,   80,   80,  177,  366,  366,  366,   80,   80,   80,

      366,   80,  178,   80,   80,   80,   80,  180,   80,  179,
      366,  181,   80,   80,   80,  366,   80,  182,   80,  183,
       80,   80,   80,   80,  184,  366,  366,   80,   80,  366,
       80,   80,   80,   80,  185,   80,   80,  186,   80,   80,
      189,   80,   80,   80,   80,   80,   80,  187,  188,  366,
       80,  366,   80,   80,   80,   80,  190,   80,  192,  366,
      191,   80,  184,   80,   80,   80,  366,  195,  193,   80,
      366,   80,   80,  194,  366,   80,  198,  366,   80,   80,
      366,   80,   80,   80,  197,   80,   80,  196,   80,   80,
      366,  199,   80,   80,   80,  200,   80,  201,   80,  212,

      212,  366,   80,   80,   80,  202,   80,  203,   80,  205,
      366,   80,   80,  155,  204,   80,  146,   80,  207,  184,
      208,   80,   80,   80,   80,   80,   80,  206,  209,  220,
      147,  184,   80,   80,  147,   80,  148,  147,   80,  146,
       80,  147,   80,  148,   80,  366,   80,   80,  146,  153,
      153,  366,  366,   80,  366,  146,  154,  366,  146,  149,
      146,  218,  218,  155,  214,  214,  149,  216,  154,  216,
      232,  158,  217,  217,  366,  219,  366,   88,  215,  161,
      161,  366,   80,  158,   80,   88,   90,  162,  162,  366,
      221,   80,  366,   91,   90,   80,  366,   80,   90,  224,

      366,   94,  366,   80,   80,   80,   90,  222,   80,   80,
       80,   80,   80,  223,  226,  184,  225,   80,   80,   80,
      366,   80,  366,  184,   80,  366,   80,   80,   80,   80,
      366,  227,   80,   80,   80,  366,   80,   80,  366,   80,
      228,   80,   80,  231,   80,   80,   80,   80,  229,  230,
      233,   80,  366,  184,   80,   80,   80,   80,   80,   80,
      234,   80,  236,  366,   80,   80,  366,  237,   80,   80,
       80,   80,   80,  235,  184,   80,   80,   80,   80,   80,
       80,  366,   80,   80,   80,  238,  366,  241,  239,   80,
       80,   80,  184,   80,  366,  240,   80,   80,   80,   80,

       80,   80,  242,  366,  366,   80,  366,   80,   80,   80,
      184,  260,  260,   80,  243,   80,   80,   80,   80,   80,
       80,  366,   80,  244,  366,  261,   80,   80,   80,  366,
       80,  246,  245,   80,   80,   80,   80,   80,  247,   80,
      366,  248,   80,   80,  366,   80,  250,   80,   80,  249,
      251,   80,  253,   80,   80,  366,  366,  366,  366,   80,
       80,   80,   80,   80,   80,   80,  252,   80,   80,   80,
      184,   80,   80,  254,  256,   80,   80,  255,   80,  257,
       80,  258,   80,   80,  366,   80,  366,   80,  366,   80,
      259,   80,   80,   80,   80,   80,   80,  366,   80,  212,

      212,  366,   80,   80,  366,  366,  154,  214,  214,  263,
      263,  264,  264,  155,  158,  218,  218,  366,  154,  266,
      266,  215,   80,  215,  270,  265,  158,  267,  366,  219,
      269,   80,  366,  219,   80,  366,   80,  268,   80,   80,
       80,   80,   80,   80,  271,  272,  184,   80,   80,  184,
       80,   80,   80,  366,   80,   80,   80,   80,   80,   80,
       80,  273,  366,   80,   80,  366,   80,   80,   80,  274,
      184,   80,  366,   80,   80,   80,   80,   80,  366,   80,
       80,  366,  275,   80,  276,  366,   80,   80,  256,   80,
      277,   80,  366,   80,  366,  366,   80,   80,  278,   80,

       80,   80,  279,   80,  366,   80,   80,   80,  281,  184,
       80,   80,  366,   80,   80,   80,   80,  280,  282,  366,
       80,   80,  366,   80,   80,   80,   80,  284,   80,  366,
       80,  285,  283,  366,  286,   80,  366,  260,  260,   80,
       80,  288,   80,   80,   80,   80,   80,  366,   80,   80,
      287,  261,   80,   80,   80,   80,   80,   80,  184,  290,
      289,  366,  366,   80,   80,   80,   80,   80,  184,  291,
       80,  366,   80,  366,   80,   80,  366,  292,  366,   80,
       80,  366,   80,   80,   80,   80,   80,  366,  366,   80,
      366,  293,   80,   80,   80,  366,   80,  294,   80,   80,

       80,   80,   80,   80,   80,  296,  295,   80,   80,  366,
      366,   80,  297,  297,   80,  366,   80,  263,  263,  264,
      264,  299,  299,   80,  158,  366,  261,  266,  266,  300,
      301,  215,  366,  265,  366,  265,  158,   80,   80,   80,
       80,  219,  303,  366,  366,  366,   80,   80,  302,   80,
       80,   80,   80,  184,  304,   80,  366,   80,   80,   80,
      366,   80,  307,   80,   80,  305,   80,   80,   80,   80,
       80,   80,  308,   80,  306,   80,   80,   80,  309,   80,
       80,   80,   80,   80,   80,  310,   80,   80,  366,   80,
       80,   80,  366,   80,  366,   80,   80,  184,  311,   80,

      366,   80,   80,  312,  366,  184,  366,  366,   80,  366,
      313,   80,  366,   80,   80,  366,   80,   80,  366,   80,
       80,  366,  315,   80,  366,   80,   80,   80,  316,  314,
      297,  297,  318,   80,   80,   80,  366,  317,   80,   80,
       80,   80,   80,   80,  261,   80,  366,   80,   80,   80,
      366,   80,   80,  319,  184,   80,  366,  320,   80,  366,
       80,  325,   80,   80,   80,   80,  184,  366,  321,   80,
      366,  322,   80,   80,  366,   80,   80,   80,   80,   80,
      299,  299,   80,  366,  366,   80,   80,   80,   80,  324,
       80,   80,  326,   80,  265,  366,   80,   80,  327,   80,

       80,   80,   80,   80,   80,   80,  366,  328,   80,  366,
      366,   80,   80,   80,   80,   80,   80,  184,   80,  329,
       80,  184,   80,   80,   80,  330,   80,   80,   80,  331,
       80,  366,  184,  184,  366,  366,   80,   80,   80,  366,
      366,   80,   80,   80,   80,   80,  184,  366,  366,  366,
       80,   80,   80,  366,   80,   80,  332,   80,   80,  366,
       80,   80,  366,   80,   80,   80,   80,   80,   80,  333,
      337,  334,   80,   80,  335,   80,  366,   80,  366,   80,
       80,  366,  366,   80,  336,   80,   80,   80,  366,   80,
      366,  366,   80,  366,  366,   80,   80,   80,  366,  184,

       80,   80,   80,   80,   80,  184,  366,  341,  340,   80,
       80,  366,  339,   80,   80,   80,   80,   80,   80,   80,
       80,  342,   80,   80,  366,  366,   80,   80,  343,   80,
       80,   80,   80,   80,  184,   80,  184,  366,   80,   80,
      344,   80,   80,   80,   80,   80,   80,   80,  347,  348,
       80,   80,  184,   80,   80,  184,  366,  349,   80,  366,
      366,   80,   80,   80,   80,   80,  366,   80,  366,  366,
       80,   80,  366,   80,   80,   80,   80,  184,   80,  184,
      184,  366,   80,  366,   80,   80,   80,  355,   80,  184,
       80,  366,  366,   80,  352,  366,   80,   80,   80,   80,

      366,   80,  366,  366,  366,   80,  366,  366,   80,   59,
       59,   59,   63,   63,   63,   66,   66,   66,   72,   72,
       72,  146,  366,  146,   11,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366
    } ;

static yyconst flex_int16_t yy_chk[1487] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    4,    3,    4,    5,    6,    5,    6,   32,
       32,   26,    3,    4,    7,    7,  373,    7,    7,   26,
        7,    8,    8,  371,    8,    8,    9,    8,    9,  363,
       10,    9,   10,   28,   18,   10,   27,   27,   28,   29,

      362,   29,   29,    7,  361,   18,   18,   46,   29,   46,
        8,   34,   34,  360,    9,   29,   46,   35,   10,   18,
       29,   27,   30,    9,   30,   30,  359,   10,   35,   35,
        9,   30,  358,    9,   10,    9,   36,   10,   30,   10,
       40,  357,   35,   30,   79,  152,   41,   36,   36,  159,
      159,   40,   40,   42,  356,   35,  354,   41,   41,  353,
       42,   36,  351,   42,  350,   40,   42,   40,   42,   79,
      152,   41,   43,  210,  210,   42,  216,  216,  346,   36,
      345,   43,   40,   43,   36,   41,   44,   41,   44,   44,
       43,   44,   45,  338,   41,  337,  325,   44,   44,   48,

       45,   48,   45,   47,   50,   45,  298,   45,   48,   47,
       47,   47,   49,   47,   45,  262,   49,   50,  213,   50,
       47,  156,   50,   53,   51,   49,   50,   49,   85,   53,
       49,   53,   74,   51,   49,   51,   69,   52,   53,   65,
       62,   61,   51,   52,   54,   52,   54,   52,   52,   55,
       52,   57,   52,   54,   66,   55,   33,   55,   66,   67,
       66,   71,   24,   67,   55,   67,   78,   80,   78,   80,
       20,   84,   84,   88,   88,   78,   80,  100,   84,  100,
       88,  100,   16,   66,   71,   84,  100,  101,   67,  101,
       84,   15,   88,   71,   11,   89,  101,   89,   89,    0,

       71,   91,   91,   71,   89,   71,    0,   90,    0,   90,
        0,   89,   90,   90,    0,   91,   89,   92,    0,   92,
       92,   93,    0,   93,   93,    0,   92,   94,   94,  154,
       93,  154,    0,   92,  154,  154,    0,   93,   92,    0,
        0,   94,   93,  102,    0,  102,  102,  103,    0,  103,
      103,  104,  102,  104,  104,  105,  103,  105,  106,  107,
      104,  107,  109,  107,  105,  110,    0,  106,  107,  106,
      108,    0,  108,  108,  108,  109,  106,  109,  110,  108,
      110,  112,  111,  111,  109,  111,    0,  110,  113,  112,
      113,  112,  111,  113,    0,    0,    0,  113,  112,  114,

        0,  114,  114,  116,  115,  116,  115,  116,  114,  115,
        0,  117,  116,  115,  117,    0,  117,  118,  118,  119,
      118,  119,  120,  117,  120,    0,    0,  118,  119,    0,
      121,  120,  121,  122,  121,  122,  123,  123,  123,  121,
      125,  125,  122,  125,  124,  123,  124,  124,  124,    0,
      125,    0,  126,  124,  126,  127,  126,  127,  129,    0,
      128,  126,  127,  128,  127,  128,    0,  131,  130,  129,
        0,  129,  128,  130,    0,  130,  134,    0,  129,  131,
        0,  131,  130,  132,  133,  132,  133,  132,  131,  134,
        0,  134,  132,  133,  135,  135,  135,  136,  134,  155,

      155,    0,  136,  135,  136,  137,  137,  138,  137,  139,
        0,  136,  138,  155,  138,  137,  149,  173,  140,  173,
      140,  138,  139,  140,  139,  140,  173,  139,  141,  163,
      146,  139,  140,  141,  146,  141,  146,  147,  163,  149,
      163,  147,  141,  147,  184,    0,  184,  163,  149,  153,
      153,    0,    0,  184,    0,  149,  153,    0,  149,  146,
      149,  160,  160,  153,  157,  157,  147,  158,  153,  158,
      177,  157,  158,  158,    0,  160,    0,  161,  157,  161,
      161,    0,  177,  157,  177,  162,  161,  162,  162,    0,
      164,  177,    0,  161,  162,  164,    0,  164,  161,  167,

        0,  162,    0,  165,  164,  165,  162,  165,  167,  166,
      167,  166,  165,  166,  169,  170,  168,  167,  166,  168,
        0,  168,    0,  171,  170,    0,  170,  169,  168,  169,
        0,  172,  171,  170,  171,    0,  169,  174,    0,  174,
      174,  171,  172,  176,  172,  175,  174,  175,  175,  175,
      178,  172,    0,  179,  175,  179,  176,  179,  176,  178,
      180,  178,  182,    0,  179,  176,    0,  183,  178,  180,
      181,  180,  181,  181,  185,  182,  185,  182,  180,  181,
      183,    0,  183,  185,  182,  186,    0,  188,  186,  183,
      186,  187,  189,  187,    0,  187,  188,  186,  188,  189,

      187,  189,  190,    0,    0,  188,    0,  190,  189,  190,
      191,  211,  211,  191,  192,  191,  190,  193,  192,  193,
      192,    0,  191,  193,    0,  211,  193,  192,  194,    0,
      194,  195,  194,  196,  195,  196,  195,  194,  196,  197,
        0,  197,  196,  195,    0,  198,  199,  198,  197,  198,
      200,  199,  202,  199,  198,    0,    0,    0,    0,  200,
      199,  200,  201,  202,  201,  202,  201,  203,  200,  203,
      203,  201,  202,  204,  206,  204,  203,  205,  205,  207,
      205,  208,  204,  206,    0,  206,    0,  205,    0,  207,
      209,  207,  206,  209,  208,  209,  208,    0,  207,  212,

      212,    0,  209,  208,    0,    0,  212,  214,  214,  215,
      215,  217,  217,  212,  214,  218,  218,    0,  212,  219,
      219,  214,  223,  215,  223,  217,  214,  220,    0,  218,
      222,  223,    0,  219,  220,    0,  220,  221,  221,  222,
      221,  222,  224,  220,  224,  225,  226,  221,  222,  227,
      226,  224,  226,    0,  225,  227,  225,  227,  228,  226,
      228,  228,    0,  225,  227,    0,  229,  228,  229,  230,
      229,  233,    0,  233,  230,  229,  230,  231,    0,  231,
      233,    0,  231,  230,  232,    0,  231,  232,  235,  232,
      234,  234,    0,  234,    0,    0,  232,  235,  236,  235,

      234,  236,  238,  236,    0,  237,  235,  237,  240,  237,
      236,  238,    0,  238,  237,  239,  241,  239,  241,    0,
      238,  240,    0,  240,  239,  241,  242,  243,  242,    0,
      240,  244,  242,    0,  245,  242,    0,  260,  260,  247,
      243,  247,  243,  245,  244,  245,  244,    0,  247,  243,
      246,  260,  245,  244,  248,  246,  248,  246,  248,  250,
      249,    0,    0,  248,  246,  249,  251,  249,  251,  252,
      250,    0,  250,    0,  249,  251,    0,  253,    0,  250,
      252,    0,  252,  253,  254,  253,  254,    0,    0,  252,
        0,  254,  253,  254,  255,    0,  255,  255,  256,  257,

      256,  257,  258,  255,  258,  259,  258,  256,  257,    0,
        0,  258,  261,  261,  259,    0,  259,  263,  263,  264,
      264,  265,  265,  259,  263,    0,  261,  266,  266,  267,
      268,  263,    0,  264,    0,  265,  263,  268,  267,  268,
      267,  266,  270,    0,    0,    0,  268,  267,  269,  271,
      269,  271,  269,  271,  272,  270,    0,  270,  271,  269,
        0,  273,  276,  273,  270,  274,  274,  272,  274,  272,
      273,  276,  277,  276,  275,  274,  272,  275,  278,  275,
      276,  278,  277,  278,  277,  279,  275,  279,    0,  279,
      278,  277,    0,  280,    0,  280,  279,  280,  281,  281,

        0,  281,  280,  282,    0,  283,    0,    0,  281,    0,
      284,  282,    0,  282,  283,    0,  283,  284,    0,  284,
      282,    0,  286,  283,    0,  285,  284,  285,  287,  285,
      297,  297,  289,  286,  285,  286,    0,  288,  288,  287,
      288,  287,  286,  289,  297,  289,    0,  288,  287,  290,
        0,  290,  289,  290,  291,  292,    0,  292,  290,    0,
      291,  302,  291,  293,  292,  293,  293,    0,  294,  291,
        0,  295,  293,  294,    0,  294,  295,  296,  295,  296,
      299,  299,  294,    0,    0,  295,  296,  300,  301,  300,
      301,  302,  303,  302,  299,    0,  300,  301,  304,  304,

      302,  304,  305,  303,  305,  303,    0,  305,  304,    0,
        0,  305,  303,  306,  307,  306,  307,  306,  308,  310,
      308,  308,  306,  307,  309,  311,  309,  308,  310,  312,
      310,    0,  313,  309,    0,    0,  311,  310,  311,    0,
        0,  313,  312,  313,  312,  311,  314,    0,    0,    0,
      313,  312,  315,    0,  315,  314,  315,  314,  316,    0,
      316,  315,    0,  317,  314,  317,  318,  316,  318,  319,
      324,  320,  317,  320,  321,  318,    0,  319,    0,  319,
      320,    0,    0,  321,  322,  321,  319,  322,    0,  322,
        0,    0,  321,    0,    0,  326,  322,  326,    0,  326,

      324,  327,  324,  327,  326,  328,    0,  331,  330,  324,
      327,    0,  329,  329,  328,  329,  328,  330,  331,  330,
      331,  332,  329,  328,    0,    0,  330,  331,  334,  334,
      332,  334,  332,  333,  333,  333,  336,    0,  334,  332,
      335,  335,  333,  335,  339,  336,  339,  336,  339,  340,
      335,  340,  341,  339,  336,  342,    0,  343,  340,    0,
        0,  341,  343,  341,  343,  342,    0,  342,    0,    0,
      341,  343,    0,  344,  342,  344,  347,  344,  347,  347,
      348,    0,  344,    0,  349,  347,  349,  352,  348,  355,
      348,    0,    0,  349,  349,    0,  352,  348,  352,  355,

        0,  355,    0,    0,    0,  352,    0,    0,  355,  367,
      367,  367,  368,  368,  368,  369,  369,  369,  370,  370,
      370,  372,    0,  372,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "jucompiler.l"
#line 2 "jucompiler.l"
/*
		Carolina de Castilho Godinho	-	2017247087
		Maria Paula de Alencar Viegas	-	2017125592
*/
#line 8 "jucompiler.l"
#include <stdbool.h> 
#include "y.tab.h"
#include "tree_functions.h"
#include "symbol_table.h"
int yyparse(void);
bool l;
bool e2;
int line_count=1;
int col_count=1;
int ini_line=1; //guarda linha em que começa comentario ou string
int ini_col=1; //guarda coluna em que começa comentario ou string
int col_escape=0;
int error_flag=0;
int col_syntax = 1;
int prev_col=1;
int prev_line=-2;
int ini_comment_line=1;
extern struct no* tree;
extern int syntax_error;




#line 928 "lex.yy.c"

#define INITIAL 0
#define COMMENT 1
#define COMMENT2 2
#define STR 3
#define ESCAPE 4

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 45 "jucompiler.l"

#line 1116 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 367 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1425 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 46 "jucompiler.l"
{
														BEGIN COMMENT2;
														col_syntax=col_count;
														col_count+=yyleng;
													}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 51 "jucompiler.l"
{
														line_count++;
														col_count=1;
														col_syntax=col_count;
														BEGIN 0;
													}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 57 "jucompiler.l"
{
														col_count+=yyleng;
														col_syntax=col_count;
													}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 61 "jucompiler.l"
{
														BEGIN COMMENT;
														ini_line=line_count;
														ini_col=col_count;
														col_count+=yyleng;
														col_syntax=col_count;
													}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 68 "jucompiler.l"
{
														col_syntax=col_count;
														col_count+=yyleng;
														BEGIN 0;
													}
	YY_BREAK
case YY_STATE_EOF(COMMENT):
#line 73 "jucompiler.l"
{
														printf("Line %d, col %d: unterminated comment\n",ini_line,ini_col);
														col_syntax=col_count;
														return 0;
													}
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 78 "jucompiler.l"
{
														line_count++;
														col_count=1;
														col_syntax=col_count;
													}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 83 "jucompiler.l"
{
														col_count+=yyleng;
														col_syntax=col_count;
														prev_col=col_count;
													}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 88 "jucompiler.l"
{
														ini_line=line_count;
														ini_col=col_count;
														col_syntax=col_count;
														col_count+=yyleng;
														BEGIN STR;
													}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 95 "jucompiler.l"
{
														col_count+=yyleng;
														col_syntax=col_count;
														col_escape=col_count-1;
														BEGIN ESCAPE;
													}
	YY_BREAK
case 10:
/* rule 10 can match eol */
YY_RULE_SETUP
#line 101 "jucompiler.l"
{
														printf("Line %d, col %d: invalid escape sequence (\\)\n",ini_line,col_escape);
														printf("Line %d, col %d: unterminated string literal\n",ini_line,ini_col);
														line_count++;
														col_count=1;
														BEGIN 0;
													}
	YY_BREAK
case 11:
/* rule 11 can match eol */
YY_RULE_SETUP
#line 108 "jucompiler.l"
{
														printf("Line %d, col %d: invalid escape sequence (\\%s)\n",ini_line,col_escape,yytext);
														col_count+=yyleng;
														error_flag=1;
														BEGIN STR;
													}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 114 "jucompiler.l"
{
														BEGIN 0;
														col_count+=yyleng;
														if(!error_flag){
															if(l){
																printf("STRLIT(\"%s)\n",yytext);
																error_flag=0;
															}
															else if(!l && e2){
																yylval.str=strdup(yytext);
																error_flag=0;
																return STRLIT;
															}
														}else{
															error_flag=0;
														}
													}
	YY_BREAK
case YY_STATE_EOF(STR):
#line 131 "jucompiler.l"
{
														printf("Line %d, col %d: unterminated string literal\n",ini_line,ini_col);
														line_count--;
														return 0;
													}
	YY_BREAK
case 13:
/* rule 13 can match eol */
YY_RULE_SETUP
#line 136 "jucompiler.l"
{
														printf("Line %d, col %d: unterminated string literal\n",ini_line,ini_col);
														line_count++;
														col_syntax=col_count;
														col_count=1;
														error_flag=0;
														BEGIN 0;
													}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 144 "jucompiler.l"
{
														col_syntax=col_count;
														col_count+=yyleng;
													}						
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 149 "jucompiler.l"
{
														col_syntax=col_count;
														col_count+=yyleng;
														if(l)
															printf("RESERVED(%s)\n",yytext);
														else if(!l && e2){
															yylval.str=strdup(yytext);
															return RESERVED;
														}	
													}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 159 "jucompiler.l"
{
														col_syntax=col_count;
														col_count+=yyleng;
														if(l)
															printf("REALLIT(%s)\n",yytext);
														else if(!l && e2){
															yylval.str=strdup(yytext);
															return REALLIT;
														}
													}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 169 "jucompiler.l"
{
														col_syntax=col_count;
														col_count+=yyleng;
														if(l)
															printf("INTLIT(%s)\n",yytext);
														else if(!l && e2){
															yylval.str=strdup(yytext);
															return INTLIT;
														}
													}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 179 "jucompiler.l"
{
														col_syntax=col_count;
														col_count+=yyleng;
														if(l)
															printf("BOOLLIT(%s)\n",yytext);
														else if(!l && e2){
															yylval.str=strdup(yytext);
															return BOOLLIT;
														}

													}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 190 "jucompiler.l"
{
														col_syntax=col_count;
														col_count+=yyleng;
														if(l)
															printf("AND\n");
														else if(!l && e2)
															return AND;

													}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 199 "jucompiler.l"
{
														col_syntax=col_count;
														col_count+=yyleng;
														if(l)
															printf("ASSIGN\n");
														else if(!l && e2)
															return ASSIGN;
													}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 207 "jucompiler.l"
{
														col_syntax=col_count;
														col_count+=yyleng;
														if(l)
															printf("STAR\n");
														else if(!l && e2)
															return STAR;
													}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 215 "jucompiler.l"
{
														col_syntax=col_count;
														col_count+=yyleng;
														if(l)
															printf("COMMA\n");
														else if(!l && e2)
															return COMMA;
													}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 223 "jucompiler.l"
{
														col_syntax=col_count;
														col_count+=yyleng;
														if(l)
															printf("DIV\n");
														else if(!l && e2)
															return DIV;
													}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 231 "jucompiler.l"
{
														col_syntax=col_count;
														col_count+=yyleng;
														if(l)
															printf("EQ\n");
														else if(!l && e2)
															return EQ;

													}	
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 240 "jucompiler.l"
{
														col_syntax=col_count;
														col_count+=yyleng;
														if(l)
															printf("GE\n");
														else if(!l && e2)
															return GE;

													}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 249 "jucompiler.l"
{
														col_syntax=col_count;
														col_count+=yyleng;
														if(l)
															printf("GT\n");
														else if(!l && e2)
															return GT;
													}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 257 "jucompiler.l"
{
														col_syntax=col_count;
														col_count+=yyleng;
														if(l)
															printf("LBRACE\n");
														else if(!l && e2)
															return LBRACE;
													}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 265 "jucompiler.l"
{
														col_syntax=col_count;
														col_count+=yyleng;
														if(l)
															printf("LE\n");
														else if(!l && e2)
															return LE;
													}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 273 "jucompiler.l"
{
														col_syntax=col_count;
														col_count+=yyleng;
														if(l)
															printf("LPAR\n");
														else if(!l && e2)
															return LPAR;
													}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 281 "jucompiler.l"
{
														col_syntax=col_count;
														col_count+=yyleng;
														if(l)
															printf("LSQ\n");
														else if(!l && e2)
															return LSQ;
													}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 289 "jucompiler.l"
{
														col_syntax=col_count;
														col_count+=yyleng;
														if(l)
															printf("LT\n");
														else if(!l && e2)
															return LT;
													}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 297 "jucompiler.l"
{
														col_syntax=col_count;
														col_count+=yyleng;
														if(l)
															printf("MINUS\n");
														else if(!l && e2)
															return MINUS;
													}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 305 "jucompiler.l"
{
														col_syntax=col_count;
														col_count+=yyleng;
														if(l)
															printf("MOD\n");
														else if(!l && e2)
															return MOD;
													}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 313 "jucompiler.l"
{
														col_syntax=col_count;
														col_count+=yyleng;
														if(l)
															printf("NE\n");
														else if(!l && e2)
															return NE;
													}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 321 "jucompiler.l"
{
														col_syntax=col_count;
														col_count+=yyleng;
														if(l)
															printf("NOT\n");
														else if(!l && e2)
															return NOT;
													}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 329 "jucompiler.l"
{
														col_syntax=col_count;
														col_count+=yyleng;
														if(l)
															printf("OR\n");
														else if(!l && e2)
															return OR;
													}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 337 "jucompiler.l"
{
														col_syntax=col_count;
														col_count+=yyleng;
														if(l)
															printf("PLUS\n");
														else if(!l && e2)
															return PLUS;
													}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 345 "jucompiler.l"
{
														col_syntax=col_count;
														col_count+=yyleng;
														if(l)
															printf("RBRACE\n");
														else if(!l && e2)
															return RBRACE;
													}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 353 "jucompiler.l"
{
														col_syntax=col_count;
														col_count+=yyleng;
														if(l)
															printf("RPAR\n");
														else if(!l && e2)
															return RPAR;
													}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 361 "jucompiler.l"
{
														col_syntax=col_count;
														col_count+=yyleng;
														if(l)
															printf("RSQ\n");
														else if(!l && e2)
															return RSQ;
													}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 369 "jucompiler.l"
{
														col_syntax=col_count;
														col_count+=yyleng;
														if(l)
															printf("SEMICOLON\n");
														else if(!l && e2)
															return SEMICOLON;
													}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 377 "jucompiler.l"
{
														col_syntax=col_count;
														col_count+=yyleng;
														if(l)
															printf("ARROW\n");
														else if(!l && e2)
															return ARROW;
													}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 385 "jucompiler.l"
{
														col_syntax=col_count;
														col_count+=yyleng;
														if(l)
															printf("LSHIFT\n");
														else if(!l && e2)
															return LSHIFT;
													}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 393 "jucompiler.l"
{
														col_syntax=col_count;
														col_count+=yyleng;
														if(l)
															printf("RSHIFT\n");
														else if(!l && e2)
															return RSHIFT;
													}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 401 "jucompiler.l"
{
														col_syntax=col_count;
														col_count+=yyleng;
														if(l)
															printf("XOR\n");
														else if(!l && e2)
															return XOR;
													}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 409 "jucompiler.l"
{
														col_syntax=col_count;
														col_count+=yyleng;
														if(l)
															printf("BOOL\n");
														else if(!l && e2)
															return BOOL;
													}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 417 "jucompiler.l"
{
														col_syntax=col_count;
														col_count+=yyleng;
														if(l)
															printf("CLASS\n");
														else if(!l && e2)
															return CLASS;
													}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 425 "jucompiler.l"
{
														col_syntax=col_count;
														col_count+=yyleng;
														if(l)
															printf("DOTLENGTH\n");
														else if(!l && e2)
															return DOTLENGTH;
													}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 433 "jucompiler.l"
{
														col_syntax=col_count;
														col_count+=yyleng;
														if(l)
															printf("DOUBLE\n");
														else if(!l && e2)
															return DOUBLE;
													}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 441 "jucompiler.l"
{
														col_syntax=col_count;
														col_count+=yyleng;
														if(l)
															printf("ELSE\n");
														else if(!l && e2)
															return ELSE;
													}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 449 "jucompiler.l"
{
														col_syntax=col_count;
														col_count+=yyleng;
														if(l)
															printf("IF\n");
														else if(!l && e2)
															return IF;
													}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 457 "jucompiler.l"
{
														col_syntax=col_count;
														col_count+=yyleng;
														if(l)
															printf("INT\n");
														else if(!l && e2)
															return INT;
													}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 465 "jucompiler.l"
{
														col_syntax=col_count;
														col_count+=yyleng;
														if(l)
															printf("PRINT\n");
														else if(!l && e2)
															return PRINT;
													}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 473 "jucompiler.l"
{
														col_syntax=col_count;
														col_count+=yyleng;
														if(l)
															printf("PARSEINT\n");
														else if(!l && e2)
															return PARSEINT;
													}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 481 "jucompiler.l"
{
														col_syntax=col_count;
														col_count+=yyleng;
														if(l)
															printf("PUBLIC\n");
														else if(!l && e2)
															return PUBLIC;
													}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 489 "jucompiler.l"
{
														col_syntax=col_count;
														col_count+=yyleng;
														if(l)
															printf("RETURN\n");
														else if(!l && e2)
															return RETURN;

													}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 498 "jucompiler.l"
{
														col_syntax=col_count;
														col_count+=yyleng;
														if(l)
															printf("STATIC\n");
														else if(!l && e2)
															return STATIC;
													}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 506 "jucompiler.l"
{
														col_syntax=col_count;
														col_count+=yyleng;
														if(l)
															printf("STRING\n");
														else if(!l && e2)
															return STRING;
													}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 514 "jucompiler.l"
{
														col_syntax=col_count;
														col_count+=yyleng;
														if(l)
															printf("VOID\n");
														else if(!l && e2)
															return VOID;
													}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 522 "jucompiler.l"
{
														col_syntax=col_count;
														col_count+=yyleng;
														if(l)
															printf("WHILE\n");
														else if(!l && e2)
															return WHILE; 
													}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 530 "jucompiler.l"
{
															col_syntax=col_count;
															col_count+=yyleng;
															if(l)
																printf("ID(%s)\n",yytext);
															else if(!l && e2){
																yylval.str=strdup(yytext);
																return ID;
															}
														}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 540 "jucompiler.l"
{
														col_count+=yyleng;
														col_syntax=col_count;
													}
	YY_BREAK
case 63:
/* rule 63 can match eol */
YY_RULE_SETUP
#line 544 "jucompiler.l"
{
														line_count++;
														col_count=1;
														col_syntax=col_count;
													}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 549 "jucompiler.l"
{
														printf("Line %d, col %d: illegal character (%s)\n",line_count,col_count,yytext);
														col_count+=yyleng;
														col_syntax=col_count;
													}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMMENT2):
case YY_STATE_EOF(ESCAPE):
#line 554 "jucompiler.l"
{
														/*
														if(line_count==prev_line+1){
															if(ini_comment_line!=line_count){
																col_syntax=prev_col;
																line_count--;
															}
														}
														*/
														return 0;
													}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 567 "jucompiler.l"
ECHO;
	YY_BREAK
#line 1995 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 367 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 367 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 366);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n, i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 567 "jucompiler.l"


int main(int argc, char **argv)
{
	if(argc == 2){
		if (strcmp(argv[1],"-l") == 0){
			l = true;
			e2 = false;
			yylex();
		}
		else if (strcmp(argv[1],"-e1") == 0){
			l = false;
			e2 = false;
			yylex();
		}
		else if(strcmp(argv[1],"-e2") == 0){
			l = false;
			e2 = true;
			yyparse();
		}
		else if	(strcmp(argv[1], "-t") == 0){
			l=false;
			e2 = true;
			yyparse();
			if(syntax_error==0)
				print_tree(tree,0);
		}
		else if(strcmp(argv[1], "-s") == 0){
			l=false;
			e2=true;
			inicia_tabela_global();
			print_symbol_table(root);
			print_tree(tree, 0);
			

		}
		else{
			return 0;
		}
	}
	else if (argc == 1){
		l = false;
		e2 = true;
		yyparse();
	}
	else{
		return 0;
	}
	return 0;
}
int yywrap()
{
	return 1;
}
